import { useState } from 'react';
import type { FormEvent } from 'react';
import { Link, Navigate, useLocation, useNavigate, useParams } from 'react-router-dom';
import { useSession } from '../features/session/SessionContext';

export function LoginPage() { const { session, login, loading, error } = useSession(); const navigate = useNavigate(); const location = useLocation(); const [message, setMessage] = useState('');
  if (session) return <Navigate to={session.organizations.length > 1 && !session.organization ? '/organizations' : '/app/conversations'} replace />;
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); try { await login(String(form.get('email')), String(form.get('password'))); navigate((location.state as { from?: string } | null)?.from ?? '/app/conversations', { replace: true }); } catch (reason) { setMessage(reason instanceof Error ? reason.message : 'Falha no login.'); } }
  return <main className="auth-layout"><section className="auth-card"><a className="brand" href="/login"><span className="brand-mark">W</span><span>WappHub <small>CHAT</small></span></a><p className="eyebrow">ATENDIMENTO EM UM SÓ LUGAR</p><h1>Entre na sua conta</h1><p className="muted">Acesse as conversas da sua organização.</p><form onSubmit={submit}><label>E-mail<input name="email" type="email" autoComplete="username" required /></label><label>Senha<input name="password" type="password" autoComplete="current-password" required /></label><button className="primary-button" disabled={loading}>{loading ? 'Entrando…' : 'Entrar'}</button></form>{(message || error) && <p role="alert" className="error-text">{message || error}</p>}<Link to="/forgot-password">Esqueci minha senha</Link></section></main>;
}
export function OrganizationsPage() { const { session, selectOrganization } = useSession(); const navigate = useNavigate(); if (!session) return <Navigate to="/login" replace />; return <main className="auth-layout"><section className="auth-card"><p className="eyebrow">CONTEXTO DE TRABALHO</p><h1>Escolha uma organização</h1><p className="muted">Você pode trocar de organização durante a sessão.</p><div className="organization-list">{session.organizations.map((org) => <button key={org.id} className="organization-option" onClick={() => void selectOrganization(org.id).then(() => navigate('/app/conversations'))}>{org.name}<span>›</span></button>)}</div></section></main>; }
export function PlaceholderPage({ title }: { title: string }) { const { conversationId, contactId, token } = useParams(); const detail = conversationId ? `Conversa ${conversationId}` : contactId ? `Contato ${contactId}` : token ? 'Convite' : ''; return <section className="page-placeholder"><div className="page-icon">◌</div><p className="eyebrow">WAPPHUB CHAT</p><h1>{title}</h1><p className="muted">A fundação do frontend está pronta. Esta área será implementada na sequência do M1.</p>{detail && <span className="detail-pill">{detail}</span>}</section>; }
export function ForgotPasswordPage() { return <PlaceholderPage title="Recuperar senha" />; }
