import { useCallback, useEffect, useRef, useState } from 'react';
import type { FormEvent } from 'react';
import { Link } from 'react-router-dom';
import { chatApi } from '../../lib/chatApi';
import { realtimeBus } from '../../lib/realtimeBus';
import type { DemoContact, InternalTextMessage, Provider } from '../../types/chat';
import { useComposerShortcut } from '../../hooks/useComposerShortcut';
import { SendPreference } from '../../components/SendPreference';
import { useSession } from '../session/SessionContext';

export function ProvidersPage() {
  const { session } = useSession();
  const [providers, setProviders] = useState<Provider[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const canManage = session?.permissions.includes('providers.manage') ?? false;
  const load = useCallback(async () => { setLoading(true); setError(''); try { setProviders((await chatApi.listProviders()).items); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível carregar provedores.'); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  async function toggle(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const enabled = !(providers.find((item) => item.code === 'DEMO')?.enabled ?? false); setBusy(true); setError(''); try { await chatApi.setDemoProvider(enabled); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível atualizar o provedor.'); } finally { setBusy(false); } }
  const demo = providers.find((item) => item.code === 'DEMO'); const meta = providers.find((item) => item.code === 'META');
  return <section className="providers-page"><header className="providers-heading"><p className="eyebrow">CONFIGURAÇÕES</p><h1>Provedores</h1><p className="muted">Gerencie os canais conectados à organização.</p></header>{loading && <p role="status">Carregando provedores…</p>}{error && <p role="alert" className="error-text">{error} <button className="text-button" onClick={() => void load()}>Tentar novamente</button></p>}{!loading && demo && <article className="provider-card"><div className="provider-card-head"><div><span className="provider-mark">D</span><div><h2>{demo.name}</h2><p>{demo.description}</p></div></div><span className={`provider-state ${demo.enabled ? 'is-enabled' : ''}`}>{demo.enabled ? 'Ativo' : 'Desativado'}</span></div><p className="provider-detail">Na primeira ativação, dois contatos de demonstração são adicionados à caixa de entrada. O histórico permanece disponível após desativar.</p><div className="provider-actions">{canManage && <form onSubmit={(event) => void toggle(event)}><button className={demo.enabled ? 'secondary-button' : 'primary-button'} disabled={busy}>{busy ? 'Salvando…' : demo.enabled ? 'Desativar Demo' : 'Ativar Demo'}</button></form>}{session?.permissions.includes('providers.simulate') && session.permissions.includes('messages.read') && <Link className="secondary-button" to="/app/providers/demo/simulator">Abrir simulador</Link>}</div></article>}{!loading && meta && <article className="provider-card provider-card-muted"><div className="provider-card-head"><div><span className="provider-mark provider-mark-muted">M</span><div><h2>{meta.name}</h2><p>{meta.description}</p></div></div><span className="provider-state">Em desenvolvimento</span></div><div className="provider-actions"><button className="secondary-button" disabled>Configuração indisponível</button></div></article>}</section>;
}

export function DemoSimulatorPage() {
  const { session } = useSession();
  const [contacts, setContacts] = useState<DemoContact[]>([]); const [enabled, setEnabled] = useState(false); const [selectedId, setSelectedId] = useState(''); const [messages, setMessages] = useState<InternalTextMessage[]>([]); const [draft, setDraft] = useState(''); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  const sendBusy = useRef(false);
  const composerShortcut = useComposerShortcut(session?.user.id);
  const canSimulate = Boolean(session?.permissions.includes('providers.simulate') && session.permissions.includes('messages.read'));
  const selected = contacts.find((contact) => contact.contactId === selectedId); const selectedConversationId = selected?.conversationId;
  const refreshMessages = useCallback(async () => { if (!selectedConversationId) { setMessages([]); return; } const page = await chatApi.listMessages(selectedConversationId); setMessages([...page.items].reverse()); }, [selectedConversationId]);
  const loadContacts = useCallback(async () => { setLoading(true); setError(''); try { const result = await chatApi.listDemoContacts(); setEnabled(result.enabled); setContacts(result.items); setSelectedId((current) => result.items.some((contact) => contact.contactId === current) ? current : result.items[0]?.contactId ?? ''); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Não foi possível carregar o simulador.'); } finally { setLoading(false); } }, []);
  useEffect(() => { if (canSimulate) void loadContacts(); }, [canSimulate, loadContacts]);
  useEffect(() => { if (!selectedConversationId) { setMessages([]); return; } let active = true; void chatApi.listMessages(selectedConversationId).then((page) => { if (active) setMessages([...page.items].reverse()); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Não foi possível carregar mensagens.')); return () => { active = false; }; }, [selectedConversationId]);
  useEffect(() => realtimeBus.subscribe((event) => { if (event.type === 'message.created' && event.payload.conversationId === selectedConversationId) void refreshMessages().catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Falha ao atualizar mensagens.')); }), [selectedConversationId, refreshMessages]);
  async function send() { const text = draft.trim(); if (sendBusy.current || !canSimulate || !text || draft.length > 8000 || !selected || !enabled) return; sendBusy.current = true; setSending(true); setError(''); setDraft(''); try { await chatApi.sendDemoMessage(selected.contactId, crypto.randomUUID(), text); await refreshMessages(); } catch (reason) { setDraft(text); setError(reason instanceof Error ? reason.message : 'Mensagem não enviada.'); } finally { sendBusy.current = false; setSending(false); } }
  if (!canSimulate) return <section className="access-denied" role="alert"><h1>Acesso indisponível</h1><p>Seu contexto não pode abrir o simulador.</p></section>;
  return <section className="demo-simulator"><header className="providers-heading"><Link to="/app/settings/providers">← Provedores</Link><p className="eyebrow">CANAL DEMO</p><h1>Simulador de contato</h1><p className="muted">Esta tela representa uma conversa do lado do cliente externo.</p></header>{!enabled && !loading && <p role="status" className="provider-warning">O Demo Provider está desativado. O histórico pode ser consultado; novas mensagens estão bloqueadas.</p>}{error && <p role="alert" className="inline-error">{error}</p>}<div className="simulator-card"><aside className="simulator-contacts" aria-label="Contatos de demonstração"><h2>Contatos</h2>{loading && <p role="status">Carregando contatos…</p>}{!loading && contacts.length === 0 && <p>Nenhum contato foi provisionado. Ative o Demo Provider em Provedores.</p>}{contacts.map((contact) => <button type="button" key={contact.contactId} aria-pressed={contact.contactId === selectedId} className={contact.contactId === selectedId ? 'selected' : ''} onClick={() => setSelectedId(contact.contactId)}>{contact.name}</button>)}</aside><section className="simulator-chat" aria-label="Conversa simulada"><header><strong>{selected?.name ?? 'Selecione um contato'}</strong><span>DEMO</span></header><div className="simulator-history" aria-live="polite">{messages.map((message) => <article className={`simulator-message ${message.direction === 'INBOUND' ? 'from-contact' : 'from-agent'}`} key={message.id}><p>{message.body}</p><time>{new Date(message.createdAt).toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit' })}</time></article>)}</div><form className="simulator-composer" onSubmit={(event) => { event.preventDefault(); void send(); }}><label className="sr-only" htmlFor="demo-message">Mensagem como contato externo</label><textarea id="demo-message" onKeyDown={(event) => composerShortcut.onKeyDown(event, () => void send())} placeholder="Escreva como o contato…" value={draft} onChange={(event) => setDraft(event.target.value)} maxLength={8000} disabled={!enabled || !selected || sending} /><div className="composer-send-controls"><button className="primary-button" disabled={!enabled || !selected || !draft.trim() || sending}>{sending ? 'Enviando…' : 'Enviar'}</button><SendPreference value={composerShortcut.shortcut} onChange={composerShortcut.setShortcut} /></div></form></section></div></section>;
}
